training_pipeline_config:
  pipeline_name: concrete
  artifact_dir: artifact

data_ingestion_config:
  author_username : elikplim
  kaggel_dataset_name : concrete-compressive-strength-data-set
  raw_data_dir: raw_data
  ingested_dir: ingested_data
  ingested_train_dir: train
  ingested_test_dir: test

data_validation_config:
  schema_dir: config
  schema_file_name: schema.yaml
  report_file_name: report.json
  report_page_file_name: report.html
