grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 2

model_selection:
  module_0:
    class: LinearRegression
    module: sklearn.linear_model
    params:
      fit_intercept: True

    search_param_grid:
      fit_intercept:
      - True
      - False

  module_1:
    class: Ridge
    module: sklearn.linear_model
    params:
      fit_intercept: True

    search_param_grid:
      fit_intercept:
        - True
        - False

  module_3:
    class: Lasso
    module: sklearn.linear_model
    params:
      fit_intercept: True

    search_param_grid:
      fit_intercept:
        - True
        - False

  module_4:
    class: DecisionTreeRegressor
    module: sklearn.tree
    params:
      criterion: squared_error

    search_param_grid:
      criterion :
        - squared_error
        - absolute_error
        - friedman_mse
        - poisson
      max_depth :
        - 2
        - 5
        - 10
        - 15
        - 20
      min_samples_split :
        - 2
        - 4
        - 8
        - 10
        - 12
      min_samples_leaf :
        - 2
        - 4
        - 6
        - 8
        - 10

  module_5:
    class: RandomForestRegressor
    module: sklearn.ensemble
    params:
      n_estimators: 40
      min_samples_leaf: 2

    search_param_grid:
      n_estimators:
        - 5
        - 10
        - 20
        - 40
        - 80
        - 100
        - 200
      criterion:
        - squared_error
        - absolute_error
        - poisson
      max_depth:
        - 2
        - 5
        - 10
        - 20
      min_samples_split:
        - 2
        - 4
        - 8
        - 12
      min_samples_leaf:
        - 2
        - 4
        - 6
        - 8
        - 10