columns:
  cement: float64
  blast_furnace_slag: float64
  fly_ash: float64
  water: float64
  superplasticizer: float64
  coarse_aggregate: float64
  fine_aggregate: float64
  age: int64
  concrete_compressive_strength: float64

target_column: concrete_compressive_strength

number_of_column : 9
